ClipTrip/ClipTrip-be

.gitignore
build.gradle
src/main/java/com/cliptripbe/global/auth/CustomerCorsFilter.java
src/main/java/com/cliptripbe/global/config/SwaggerConfig.java

1. https 설정을 하지 않은 Swagger Config를 추가했습니다.
2. 미리 Cors Filiter를 추가했습니다.

Swagger, Cors Filter 추가

---

build.gradle
src/main/java/com/cliptripbe/feature/user/api/UserController.java
src/main/java/com/cliptripbe/feature/user/api/UserControllerDocs.java
src/main/java/com/cliptripbe/feature/user/api/dto/request/UserSignInRequestDto.java
src/main/java/com/cliptripbe/feature/user/api/dto/request/UserSignUpRequestDto.java
src/main/java/com/cliptripbe/feature/user/api/dto/response/UserInfoResponse.java
src/main/java/com/cliptripbe/feature/user/application/UserChecker.java
src/main/java/com/cliptripbe/feature/user/application/UserLoader.java
src/main/java/com/cliptripbe/feature/user/application/UserService.java
src/main/java/com/cliptripbe/feature/user/domain/User.java
src/main/java/com/cliptripbe/feature/user/domain/type/Age.java
src/main/java/com/cliptripbe/feature/user/domain/type/Language.java
src/main/java/com/cliptripbe/feature/user/domain/type/Role.java
src/main/java/com/cliptripbe/feature/user/infrastructure/UserRepository.java
src/main/java/com/cliptripbe/global/auth/AuthService.java
src/main/java/com/cliptripbe/global/auth/cors/CustomerCorsFilter.java
src/main/java/com/cliptripbe/global/auth/jwt/JwtAuthenticationFilter.java
src/main/java/com/cliptripbe/global/auth/jwt/component/JwtTokenProvider.java
src/main/java/com/cliptripbe/global/auth/jwt/entity/JwtToken.java
src/main/java/com/cliptripbe/global/auth/jwt/entity/TokenDto.java
src/main/java/com/cliptripbe/global/auth/security/CustomerDetails.java
src/main/java/com/cliptripbe/global/auth/security/CustomerDetailsService.java
src/main/java/com/cliptripbe/global/config/SecurityConfig.java
src/main/java/com/cliptripbe/global/response/ApiResponse.java
src/main/java/com/cliptripbe/global/response/exception/CustomException.java
src/main/java/com/cliptripbe/global/response/exception/GlobalExceptionHandler.java
src/main/java/com/cliptripbe/global/response/type/ErrorType.java
src/main/java/com/cliptripbe/global/response/type/ResultType.java
src/main/java/com/cliptripbe/global/response/type/SuccessType.java

1. 회원가입할 때 필요한 전체 데이터를 다 받진 않고 간략하게만 구현헀습니다.
2. Security를 적용했습니다.
3. Jwt 적용했습니다. jwt 비밀키는 노션으로 공유하겠습니다.

[Feat]User 회원가입,로그인 API 구현 및 Security, jwt 적용 완료

---

.github/workflows/ci.yml

java set에 distribution 추가

---

.github/workflows/ci.yml

build시 test는 제외한다.

---

.idea/.gitignore
.idea/compiler.xml
.idea/dataSources.xml
.idea/gradle.xml
.idea/jarRepositories.xml
.idea/misc.xml
.idea/modules.xml
.idea/uiDesigner.xml
.idea/vcs.xml

xml 파일 깃 추적

---

src/main/java/com/cliptripbe/feature/user/api/dto/request/UserSignInRequestDto.java
src/main/java/com/cliptripbe/feature/user/api/dto/request/UserSignUpRequestDto.java
src/main/java/com/cliptripbe/feature/user/api/dto/response/UserInfoResponse.java
src/main/java/com/cliptripbe/feature/user/application/UserChecker.java
src/main/java/com/cliptripbe/feature/user/application/UserLoader.java
src/main/java/com/cliptripbe/feature/user/application/UserService.java
src/main/java/com/cliptripbe/feature/user/domain/User.java
src/main/java/com/cliptripbe/feature/user/domain/type/AgeGroup.java
src/main/java/com/cliptripbe/feature/user/domain/type/Gender.java
src/main/java/com/cliptripbe/feature/user/domain/type/Language.java
src/main/java/com/cliptripbe/feature/user/infrastructure/UserRepository.java
src/main/java/com/cliptripbe/global/auth/security/CustomerDetails.java
src/main/java/com/cliptripbe/global/auth/security/CustomerDetailsService.java

[feat/refactor] 유저 나이,언어,성별 속성 추가 및 로그인시 이메일

---

src/main/java/com/cliptripbe/feature/place/api/PlaceController.java
src/main/java/com/cliptripbe/feature/schedule/api/ScheduleController.java
src/main/java/com/cliptripbe/feature/user/api/UserController.java
src/main/java/com/cliptripbe/feature/video/api/VideoController.java
src/main/java/com/cliptripbe/global/config/Constant.java

[refactor] URL 버전 맞추기

---

src/main/java/com/cliptripbe/feature/schedule/api/ScheduleController.java
src/main/java/com/cliptripbe/feature/schedule/api/dto/request/CreateScheduleRequestDto.java
src/main/java/com/cliptripbe/feature/schedule/api/dto/request/DeleteSchedulePlaceRequestDto.java
src/main/java/com/cliptripbe/feature/schedule/api/dto/response/ScheduleListResponseDto.java
src/main/java/com/cliptripbe/feature/schedule/application/SchedulePlaceMapper.java
src/main/java/com/cliptripbe/feature/schedule/application/ScheduleService.java
src/main/java/com/cliptripbe/feature/schedule/domain/entity/Schedule.java

[refactor] 일정에 설명 속성 추가, 응답값 최적화

---

src/main/java/com/cliptripbe/feature/bookmark/api/BookmarkController.java
src/main/java/com/cliptripbe/feature/bookmark/application/BookmarkFinder.java
src/main/java/com/cliptripbe/feature/bookmark/application/BookmarkService.java
src/main/java/com/cliptripbe/feature/bookmark/infrastructure/BookmarkRepository.java
src/main/java/com/cliptripbe/feature/place/application/PlaceMapper.java
src/main/java/com/cliptripbe/feature/place/domain/entity/Place.java
src/main/java/com/cliptripbe/feature/place/domain/type/PlaceType.java
src/main/java/com/cliptripbe/feature/place/infrastructure/PlaceRepository.java
src/main/java/com/cliptripbe/infrastructure/file/FileKind.java
src/main/java/com/cliptripbe/infrastructure/inital/DataInitializer.java
src/main/java/com/cliptripbe/infrastructure/inital/initaler/BookmarkInitializer.java
src/main/java/com/cliptripbe/infrastructure/inital/initaler/PlaceInitializer.java

[feat/refactor] 관리하는 장소 및 물품 보관함 서울의 북마크 데이터를 기본으로 만드는 로직 추가 및 placet ype 추가

---

src/main/java/com/cliptripbe/feature/bookmark/api/BookmarkController.java
src/main/java/com/cliptripbe/feature/bookmark/api/BookmarkControllerDocs.java
src/main/java/com/cliptripbe/feature/bookmark/api/dto/request/CreateBookmarkRequestDto.java
src/main/java/com/cliptripbe/feature/bookmark/api/dto/request/UpdateBookmarkRequestDto.java
src/main/java/com/cliptripbe/feature/bookmark/application/BookmarkFinder.java
src/main/java/com/cliptripbe/feature/bookmark/application/BookmarkService.java
src/main/java/com/cliptripbe/feature/bookmark/domain/entity/Bookmark.java
src/main/java/com/cliptripbe/feature/bookmark/infrastructure/BookmarkRepository.java
src/main/java/com/cliptripbe/feature/place/api/PlaceController.java
src/main/java/com/cliptripbe/feature/place/api/PlaceControllerDocs.java
src/main/java/com/cliptripbe/feature/place/api/dto/PlaceInfoRequestDto.java
src/main/java/com/cliptripbe/feature/place/api/dto/response/PlaceAccessibilityInfoResponse.java
src/main/java/com/cliptripbe/feature/place/application/PlaceFinder.java
src/main/java/com/cliptripbe/feature/place/application/PlaceService.java
src/main/java/com/cliptripbe/feature/user/domain/User.java

[feat/refactor] 북마크 추가 삭제 api를 put으로 대체 / 장소 카드에서 북마크 표시를 위한 처리 추가

---

src/main/java/com/cliptripbe/feature/place/api/PlaceController.java
src/main/java/com/cliptripbe/feature/place/api/PlaceControllerDocs.java
src/main/java/com/cliptripbe/feature/place/api/dto/PlaceDto.java
src/main/java/com/cliptripbe/feature/place/api/dto/request/PlaceSearchByCategoryRequestDto.java
src/main/java/com/cliptripbe/feature/place/api/dto/request/PlaceSearchByKeywordRequestDto.java
src/main/java/com/cliptripbe/feature/place/api/dto/response/PlaceListResponseDto.java
src/main/java/com/cliptripbe/feature/place/api/dto/response/PlaceResponseDto.java
src/main/java/com/cliptripbe/feature/place/application/PlaceService.java
src/main/java/com/cliptripbe/feature/place/domain/type/PlaceCategory.java
src/main/java/com/cliptripbe/global/response/type/ErrorType.java
src/main/java/com/cliptripbe/infrastructure/kakao/KakaoMapService.java
src/main/java/com/cliptripbe/infrastructure/kakao/dto/KakaoMapResponse.java

feat: 카테고리, 키워드를 통해 장소리스트 조회 구현

---

src/main/java/com/cliptripbe/feature/place/api/dto/PlaceInfoRequestDto.java
src/main/java/com/cliptripbe/feature/place/application/PlaceMapper.java
src/main/java/com/cliptripbe/feature/place/application/PlaceRegister.java
src/main/java/com/cliptripbe/infrastructure/file/FileKind.java
src/main/java/com/cliptripbe/infrastructure/inital/DataInitializer.java
src/main/java/com/cliptripbe/infrastructure/inital/initaler/BookmarkInitializer.java
src/main/java/com/cliptripbe/infrastructure/inital/initaler/PlaceInitializer.java
src/main/java/com/cliptripbe/infrastructure/inital/type/DefaultData.java

[refactor] PlaceInfoRequestDto에 PlaceType 받도록 수정

---

build.gradle
src/main/java/com/cliptripbe/feature/place/api/PlaceController.java
src/main/java/com/cliptripbe/feature/place/api/PlaceControllerDocs.java
src/main/java/com/cliptripbe/feature/place/api/dto/request/PlaceSearchByCategoryRequestDto.java
src/main/java/com/cliptripbe/feature/place/api/dto/request/PlaceSearchByKeywordRequestDto.java
src/main/java/com/cliptripbe/feature/place/domain/entity/Place.java
src/main/java/com/cliptripbe/global/config/S3Config.java
src/main/java/com/cliptripbe/global/config/WebClientConfig.java
src/main/java/com/cliptripbe/global/response/type/ErrorType.java
src/main/java/com/cliptripbe/infrastructure/file/FileService.java
src/main/java/com/cliptripbe/infrastructure/google/dto/GooglePlacesSearchResponse.java
src/main/java/com/cliptripbe/infrastructure/google/service/GooglePlacesService.java
src/main/java/com/cliptripbe/infrastructure/inital/initaler/PlaceInitializer.java
src/main/java/com/cliptripbe/infrastructure/s3/S3Service.java
src/main/resources/application-local.yml
src/test/java/com/cliptripbe/place/PlaceTest.java

Feat: google places를 통해 장소 이미지 가져오기 / S3 upload 구현

---

src/main/java/com/cliptripbe/feature/video/api/dto/request/ExtractPlaceRequestDto.java
src/main/java/com/cliptripbe/feature/video/api/dto/response/VideoResponseDto.java
src/main/java/com/cliptripbe/feature/video/application/VideoService.java
src/main/java/com/cliptripbe/feature/video/domain/Video.java
src/main/java/com/cliptripbe/infrastructure/openai/prompt/PromptConstants.java
src/main/resources/application-local.yml

refactor: 영상 요약시 유저가 english 선택했을 경우 번역본 응답

---

src/main/java/com/cliptripbe/feature/bookmark/api/BookmarkController.java
src/main/java/com/cliptripbe/feature/bookmark/api/BookmarkControllerDocs.java
src/main/java/com/cliptripbe/feature/bookmark/application/BookmarkMapper.java
src/main/java/com/cliptripbe/feature/bookmark/application/BookmarkService.java
src/main/java/com/cliptripbe/feature/place/api/dto/response/PlaceListResponseDto.java
src/main/java/com/cliptripbe/feature/schedule/api/ScheduleController.java
src/main/java/com/cliptripbe/feature/schedule/api/ScheduleControllerDocs.java
src/main/java/com/cliptripbe/feature/schedule/application/SchedulePlaceMapper.java
src/main/java/com/cliptripbe/feature/schedule/application/ScheduleService.java

[feat] 북마크, 일정내의 장소 리스트도 번역이 필요한 경우 변역되도록 구현

---

src/main/java/com/cliptripbe/feature/bookmark/application/BookmarkMapper.java
src/main/java/com/cliptripbe/feature/bookmark/application/BookmarkService.java

기본 북마크 정보 제공 장소 10개로 한정 짓도록 변경

---

build.gradle

[build] health check를 위한 의존성 추가

---

src/main/java/com/cliptripbe/feature/bookmark/api/BookmarkController.java
src/main/java/com/cliptripbe/feature/bookmark/domain/entity/Bookmark.java
src/main/java/com/cliptripbe/feature/user/application/UserService.java

[refactor] 유저가 회원가입하면 북마크를 갖도록 구현 변경

---

src/main/java/com/cliptripbe/feature/place/api/dto/PlaceDto.java
src/main/resources/application-local.yml

refactor: 장소 추출시 도로명 주소가 없을 때 지번주소 등록 및 카테고리 저장 및 응답

---

src/main/java/com/cliptripbe/feature/user/api/UserController.java
src/main/java/com/cliptripbe/feature/user/api/UserControllerDocs.java
src/main/java/com/cliptripbe/feature/user/api/dto/response/UserLoginResponse.java
src/main/java/com/cliptripbe/feature/user/application/UserService.java

[refactor] 로그인시 유저가 선택한 언어 정보도 제공하도록 변경

---

src/main/java/com/cliptripbe/global/auth/jwt/JwtAuthenticationFilter.java

이미지 확인용입니다.

---

.github/workflows/cd.yml

refactor: cd 파일 수정 (elb -> ec2 단일 배포 환경)

---

.github/workflows/ci-cd.yml

latest-> 변수로 변경

---

src/main/java/com/cliptripbe/feature/translate/application/PlaceTranslationService.java

refactor: List<Place> placeEntityList로 한번에 저장시에 중복 체크하고 저장하도록 변경
